namespace FieldEvents.Shared.Contracts;

/// <summary>
/// Message the Agent pushes to the Server's EventsHub. OutboxId is generated by the Agent
/// and is the idempotency key: the Server ignores duplicate OutboxIds so a retried
/// (previously-unacked) send never creates the event twice.
/// </summary>
public sealed class AgentEventMessage
{
    public Guid OutboxId { get; set; }
    public string SourceId { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string? Location { get; set; }
    public EventPriority Priority { get; set; } = EventPriority.Normal;
    public string? ExternalRef { get; set; }
    public DateTimeOffset OccurredAtUtc { get; set; }
}
